**Código Adaline**

In [ ]:
import numpy as np
#X = [1,2,3,4,5]
#ADALINE
# 3*X+2*1 #intercept
#X**1 , X**0 -> 3*X**1 + 3*X**0
#
X_adj = np.array( [ [1,1], [2,1],[3,1],[4,1],[5,1] ])
noise = np.random.normal(0, 0.5, 5)
Y = np.array( [5,8,11,14,17] ) #+noise  #7*x + 11 [17.4337829 , 25.59115513, 32.47831352, 39.47945572, 46.44298563]
W = np.random.rand(2)
n=0.01
erro=0
somatorioErro=0
iteracoes = 1000
for j in range(iteracoes):
  for i in range(len(X_adj)):
    net = X_adj[i,:].dot(W) # x1*x1 + x2*w2 +...+xn*wn + b*1
    #funçao de ativação linear
    erro =(Y[i]-net)
    W = W +n*erro*X_adj[i,:]
    somatorioErro=somatorioErro+erro**2
  print('Erro =%f'%(somatorioErro))
  somatorioErro=0



Erro =224.574080
Erro =62.901275
Erro =19.165703
Erro =7.287675
Erro =4.031807
Erro =3.118028
Erro =2.844836
Erro =2.749155
Erro =2.703911
Erro =2.673711
Erro =2.648436
Erro =2.625066
Erro =2.602634
Erro =2.580803
Erro =2.559440
Erro =2.538486
Erro =2.517912
Erro =2.497700
Erro =2.477839
Erro =2.458321
Erro =2.439138
Erro =2.420283
Erro =2.401752
Erro =2.383538
Erro =2.365635
Erro =2.348039
Erro =2.330743
Erro =2.313743
Erro =2.297034
Erro =2.280611
Erro =2.264469
Erro =2.248602
Erro =2.233006
Erro =2.217677
Erro =2.202610
Erro =2.187801
Erro =2.173244
Erro =2.158936
Erro =2.144872
Erro =2.131048
Erro =2.117460
Erro =2.104105
Erro =2.090977
Erro =2.078073
Erro =2.065390
Erro =2.052922
Erro =2.040668
Erro =2.028622
Erro =2.016782
Erro =2.005144
Erro =1.993704
Erro =1.982459
Erro =1.971406
Erro =1.960541
Erro =1.949862
Erro =1.939364
Erro =1.929045
Erro =1.918902
Erro =1.908931
Erro =1.899131
Erro =1.889497
Erro =1.880027
Erro =1.870718
Erro =1.861568
Erro =1.852573
Erro =1.843731
Erro =

In [ ]:
W

array([4.06672746, 1.72149784])

In [ ]:
Y

array([17.4337829 , 25.59115513, 32.47831352, 39.47945572, 46.44298563])

**Código Mínimos Quadrados**

In [ ]:
import numpy as np

#X = [1,2,3,4,5]
# 3X+2 #intercept
#X**1 , X**0 -> 3*X**1 + 3*X**0

X_adj = np.array( [ [1,1], [2,1],[3,1],[4,1],[5,1] ])
noise = np.random.normal(0, 0.2, 5)
Y = np.array([5,8,11,14,17]  )#+noise
#linalg

W = np.linalg.pinv(X_adj).dot(Y) #    X*W =Y, X^(-1)*X*W = X^(-1)*Y = W = X^(-1)*Y

predicted=X_adj.dot(W)

mse = np.mean((Y-predicted)**2)
print(mse)

3.7865323450608565e-30


In [ ]:
W

array([ 7., 11.])

In [ ]:
W

array([3., 2.])

array([ 4.4201466 ,  8.0592759 , 11.69840521, 15.33753451, 18.97666381])

In [ ]:
import numpy as np

X_adj = np.array( [ [1,1], [2,1],[3,1],[4,1],[5,1] ])
x_inv = np.linalg.pinv(X_adj)

**Sistema Híbrido**


In [ ]:
import numpy as np
#X = [1,2,3,4,5]
#ADALINE
# 3X+2 #intercept
#X**1 , X**0 -> 3*X**1 + 3*X**0

X_adj = np.array( [ [1,1], [2,1],[3,1],[4,1],[5,1] ])
noise = np.random.normal(0, 0.2, 5)
Y = np.array( [5,8,11,14,17] ) +noise
W = np.linalg.pinv(X_adj).dot(Y) #
n=0.00001
erro=0
somatorioErro=0
iteracoes = 1000
for j in range(iteracoes):
  for i in range(len(X_adj)):
    net = X_adj[i,:].dot(W)
    #funçao de ativação linear
    erro =(Y[i]-net)
    W = W +n*erro*X_adj[i,:]
    somatorioErro=somatorioErro+erro**2
  print('Erro =%f'%(somatorioErro))
  somatorioErro=0


Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.073676
Erro =0.07

In [ ]:
X_adj.dot(W)

array([ 4.3375784 ,  7.95309146, 11.56860452, 15.18411759, 18.79963065])